In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [17]:
import warnings
warnings.filterwarnings('ignore')

## Veri Setini Yükle

In [18]:
df = pd.read_csv('car_evaluation.csv')
#df = pd.read_csv(data, header=None)

### Keşifsel veri analizi

In [19]:
# veri kümesinin boyutlarını görüntüleme
df.shape
#Veri setinde 1728 örnek ve 7 değişken olduğunu görebiliyoruz

(1727, 7)

In [20]:
df.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

Sütun adlarını yeniden adlandırın
Veri kümesinin uygun sütun adlarına sahip olmadığını görebiliriz. Sütunlar yalnızca 0,1,2.... ve benzeri şekilde etiketlenmiştir. Sütunlara uygun isimler vermeliyiz.

In [21]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_names
col_names

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [22]:
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1727 non-null   object
 1   maint     1727 non-null   object
 2   doors     1727 non-null   object
 3   persons   1727 non-null   object
 4   lug_boot  1727 non-null   object
 5   safety    1727 non-null   object
 6   class     1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

Değişkenlerdeki değerlerin frekans dağılımı
Şimdi kategorik değişkenlerin frekans sayılarını kontrol edelim.

In [24]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
for col in col_names:
    print(df[col].value_counts())

high     432
med      432
low      432
vhigh    431
Name: buying, dtype: int64
high     432
med      432
low      432
vhigh    431
Name: maint, dtype: int64
3        432
4        432
5more    432
2        431
Name: doors, dtype: int64
4       576
more    576
2       575
Name: persons, dtype: int64
med      576
big      576
small    575
Name: lug_boot, dtype: int64
med     576
high    576
low     575
Name: safety, dtype: int64
unacc    1209
acc       384
good       69
vgood      65
Name: class, dtype: int64

### Değişkenlerin özeti
-Veri setinde 7 değişken bulunmaktadır. Tüm değişkenler kategorik veri tipindedir.
-buying, maint, doors, persons, lug_boot, safety and class.
-class hedef değişkendir.

### Özellik vektörünü ve hedef değişkeni belirle

In [25]:
X=  df.drop(['class'], axis=1)
y = df['class']

### Eğitim ve Test Kümesi Ayır

In [26]:
from sklearn.model_selection import train_test_split
#print(X.isnull().sum().sum())
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [27]:
# X_train and X_test örnek sayısı
X_train.shape, X_test.shape 
print(type (X_train))

<class 'pandas.core.frame.DataFrame'>

###  Öznitelik Mühendisliği
Özellik Mühendisliği, ham verileri modelimizi daha iyi anlamamıza ve tahmin gücünü artırmamıza yardımcı olan yararlı özelliklere dönüştürme sürecidir. Özellik mühendisliğini farklı değişken türleri üzerinde gerçekleştireceğim.

In [28]:
# check data types in X_train
X_train.dtypes
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>

In [29]:
X_train.head()

     buying  maint  doors persons lug_boot safety
83    vhigh  vhigh  5more       2      med    low
48    vhigh  vhigh      3    more      med    med
468    high  vhigh      3       4    small    med
155   vhigh   high      3    more      med    low
1043    med   high      4    more    small    low

We can see that all the variables are ordinal categorical data type

In [30]:
#import category encoders
from sklearn.preprocessing import OrdinalEncoder

In [31]:
# encode categorical variables with ordinal encoding
encoder = OrdinalEncoder()
X_train= pd.DataFrame(encoder.fit_transform(np.array(X_train)))
X_test = pd.DataFrame(encoder.fit_transform(X_test))

In [32]:
X_train.head()

     0    1    2    3    4    5
0  3.0  3.0  3.0  0.0  1.0  1.0
1  3.0  3.0  1.0  2.0  1.0  2.0
2  0.0  3.0  1.0  1.0  2.0  2.0
3  3.0  0.0  1.0  2.0  1.0  1.0
4  2.0  0.0  2.0  2.0  2.0  1.0

###  Varsayılan parametrelerle Rastgele Orman Sınıflandırıcı modeli

In [36]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier (random_state=0)

rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)

from sklearn.metrics import accuracy_score

print('Modelin 10 karar ağacıyla doğruluk değeri: (0:0.4f)'. format(accuracy_score(y_test, y_pred)))

Modelin 10 karar ağacıyla doğruluk değeri: (0:0.4f)

###  n_estimators=100 parametresi ile Rastgele Orman Sınıflandırıcı modeli

In [ ]:
rfc_100 Random ForestClassifier(n_estimators=100, random_state=0)
rfc_100.fit(X_train, y_train)
y_pred_100 rfc_100.predict(X_test)
print('Modelin 100 karar ağacıyla doğruluk değeri:: {0:0.4f)'. format(accuracy_score(y_test, y_pred_100)))